//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMBIENTE_IMAGEM
    {
        public int AMIM_CD_ID { get; set; }
        public int AMBI_CD_ID { get; set; }
        public string AMIM_NM_ARQUIVO { get; set; }
        public int AMIM_IN_TIPO { get; set; }
        public System.DateTime AMIM_DT_CADASTRO { get; set; }
        public int AMIM_IN_ATIVO { get; set; }
        public string AMIN_NM_TITULO { get; set; }
    
        public virtual AMBIENTE AMBIENTE { get; set; }
    }
}
