//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROLE_VEICULO
    {
        public int COVE_CD_ID { get; set; }
        public Nullable<int> TIVE_CD_ID { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public Nullable<int> FUCR_CD_ID { get; set; }
        public Nullable<int> COND_CD_ID { get; set; }
        public Nullable<System.DateTime> COVE_DT_ENTRADA { get; set; }
        public Nullable<System.DateTime> COVE_DT_SAIDA { get; set; }
        public string COVE_NM_PLACA { get; set; }
        public string COVE_NM_MARCA { get; set; }
        public string COVE_DS_DESCRICAO { get; set; }
        public int COVE_IN_ATIVO { get; set; }
        public string COVE_NM_MODELO { get; set; }
        public string COVE_NM_COR { get; set; }
        public Nullable<System.DateTime> COVE_DT_PREVISAO_SAIDA { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual TIPO_VEICULO TIPO_VEICULO { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
    }
}
