//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONVIDADO
    {
        public int CONV_CD_ID { get; set; }
        public int LICO_CD_ID { get; set; }
        public string CONV_NM_CONVIDADO { get; set; }
        public int CONV_IN_CHEGOU { get; set; }
        public System.DateTime CONV_DT_CADASTRO { get; set; }
        public int CONV_IN_ATIVO { get; set; }
    
        public virtual LISTA_CONVIDADO LISTA_CONVIDADO { get; set; }
    }
}
