//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORPO_DIRETIVO
    {
        public int CODI_CD_ID { get; set; }
        public int COND_CD_ID { get; set; }
        public int PROP_CD_ID { get; set; }
        public int FUCO_CD_ID { get; set; }
        public System.DateTime CODI_DT_INICIO { get; set; }
        public Nullable<System.DateTime> CODI_DT_FINAL { get; set; }
        public string CODI_TX_OBSERVACOES { get; set; }
        public System.DateTime CODI_DT_CADASTRO { get; set; }
        public int CODI_IN_ATIVO { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        public virtual FUNCAO_CORPO_DIRETIVO FUNCAO_CORPO_DIRETIVO { get; set; }
        public virtual PROPRIETARIO PROPRIETARIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
