//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPENDENTE
    {
        public int DEPE_CD_ID { get; set; }
        public int FUCR_CD_ID { get; set; }
        public int SEXO_CD_ID { get; set; }
        public int GRPA_CD_ID { get; set; }
        public string DEPE_NM_NOME { get; set; }
        public System.DateTime DEPE_DT_NASCIMENTO { get; set; }
        public System.DateTime DEPE_DT_CADASTRO { get; set; }
        public int DEPE_IN_ATIVO { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual GRAU_PARENTESCO GRAU_PARENTESCO { get; set; }
        public virtual SEXO SEXO { get; set; }
    }
}
