//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCOMENDA_ANEXO
    {
        public int ENAN_CD_ID { get; set; }
        public int ENCO_CD_ID { get; set; }
        public string ENAN_NM_TITULO { get; set; }
        public int ENAN_IN_TIPO { get; set; }
        public System.DateTime ENAN_DT_ANEXO { get; set; }
        public string ENAN_AQ_ARQUIVO { get; set; }
        public int ENAN_IN_ATIVO { get; set; }
    
        public virtual ENCOMENDA ENCOMENDA { get; set; }
    }
}
