//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORECIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAVORECIDO()
        {
            this.MOVIMENTO = new HashSet<MOVIMENTO>();
        }
    
        public int FAVO_CD_ID { get; set; }
        public int COND_CD_ID { get; set; }
        public int TIFA_CD_ID { get; set; }
        public string FAVO_NM_NOME { get; set; }
        public System.DateTime FAVO_DT_CADASTRO { get; set; }
        public int FAVO_IN_ATIVO { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        public virtual TIPO_FAVORECIDO TIPO_FAVORECIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMENTO> MOVIMENTO { get; set; }
    }
}
