//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRUPO()
        {
            this.DOCUMENTO = new HashSet<DOCUMENTO>();
            this.METADADO = new HashSet<METADADO>();
            this.SUBGRUPO = new HashSet<SUBGRUPO>();
            this.CENTRO_CUSTO = new HashSet<CENTRO_CUSTO>();
        }
    
        public int GRUP_CD_ID { get; set; }
        public string GRUP_NM_NOME { get; set; }
        public System.DateTime GRUP_DT_CADASTRO { get; set; }
        public int GRUP_IN_ATIVO { get; set; }
        public Nullable<int> COND_CD_ID { get; set; }
        public string GR_NM_EXIBE { get; set; }
        public string GRUP_NR_NUMERO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METADADO> METADADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBGRUPO> SUBGRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CENTRO_CUSTO> CENTRO_CUSTO { get; set; }
    }
}
