//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_NEGRA
    {
        public int LINE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> GRPA_CD_ID { get; set; }
        public string LINE_NM_VISITANTE { get; set; }
        public string LINE_NR_DOCUMENTO { get; set; }
        public string LINE_DS_MOTIVO { get; set; }
        public string LINE_NM_EMPRESA { get; set; }
        public int LINE_IN_AVISO { get; set; }
        public int LINE_IN_PERMANENTE { get; set; }
        public Nullable<System.DateTime> LINE_DT_LIMITE { get; set; }
        public string LINE_DS_OBSERVACAO { get; set; }
        public System.DateTime LINE_DT_CADASTRO { get; set; }
        public int LINE_IN_ATIVO { get; set; }
        public Nullable<int> COND_CD_ID { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public Nullable<System.DateTime> LINE_DT_VISITA { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        public virtual GRAU_PARENTESCO GRAU_PARENTESCO { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
