//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MORADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MORADOR()
        {
            this.AMBIENTE_CHAVE = new HashSet<AMBIENTE_CHAVE>();
            this.CONTA_RECEBER = new HashSet<CONTA_RECEBER>();
            this.ENCOMENDA = new HashSet<ENCOMENDA>();
            this.LISTA_CONVIDADO = new HashSet<LISTA_CONVIDADO>();
            this.OCORRENCIA = new HashSet<OCORRENCIA>();
        }
    
        public int MORA_CD_ID { get; set; }
        public int COND_CD_ID { get; set; }
        public int UNID_CD_ID { get; set; }
        public string MORA_NR_CPF { get; set; }
        public string MORA_NM_NOME { get; set; }
        public System.DateTime MORA_DT_NASCIMENTO { get; set; }
        public string MORA_NM_EMAIL { get; set; }
        public string MORA_NR_TELEFONE { get; set; }
        public string MORA_NR_CELULAR { get; set; }
        public int MORA_IN_ATUAL { get; set; }
        public int MORA_IN_RESPONSAVEL { get; set; }
        public Nullable<System.DateTime> MORA_DT_ENTRADA { get; set; }
        public Nullable<System.DateTime> MORA_DT_SAIDA { get; set; }
        public string MORA_TX_OBSERVACOES { get; set; }
        public System.DateTime MORA_DT_CADASTRO { get; set; }
        public int MORA_IN_ATIVO { get; set; }
        public int MORA_IN_PROPRIETARIO { get; set; }
        public string MORA_AQ_FOTO { get; set; }
        public Nullable<int> TORR_CD_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMBIENTE_CHAVE> AMBIENTE_CHAVE { get; set; }
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_RECEBER> CONTA_RECEBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCOMENDA> ENCOMENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_CONVIDADO> LISTA_CONVIDADO { get; set; }
        public virtual TORRE TORRE { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCORRENCIA> OCORRENCIA { get; set; }
    }
}
