//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIMENTO()
        {
            this.TAXA_CONDOMINIO = new HashSet<TAXA_CONDOMINIO>();
        }
    
        public int MOVI_CD_ID { get; set; }
        public int COND_CD_ID { get; set; }
        public Nullable<int> COBA_CD_ID { get; set; }
        public Nullable<int> FAVO_CD_ID { get; set; }
        public Nullable<int> PLCO_CD_ID { get; set; }
        public Nullable<int> TIMO_CD_ID { get; set; }
        public System.DateTime MOVI_DT_MOVIMENTO { get; set; }
        public string MOVI_DS_HISTORICO { get; set; }
        public int MOVI_IN_PAGAMENTO { get; set; }
        public string MOVI_NR_DOCUMENTO { get; set; }
        public decimal MOVI_VL_VALOR { get; set; }
        public int MOVI_IN_EXECUTADO { get; set; }
        public int MOVI_IN_CONCILIADO { get; set; }
        public int MOVI_IN_ATIVO { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        public virtual CONTA_BANCO CONTA_BANCO { get; set; }
        public virtual FAVORECIDO FAVORECIDO { get; set; }
        public virtual PLANO_CONTA PLANO_CONTA { get; set; }
        public virtual TIPO_MOVIMENTO TIPO_MOVIMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAXA_CONDOMINIO> TAXA_CONDOMINIO { get; set; }
    }
}
