//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCORRENCIA_ANEXO
    {
        public int OCAN_CD_ID { get; set; }
        public Nullable<int> OCOR_CD_ID { get; set; }
        public Nullable<int> OCCO_CD_ID { get; set; }
        public Nullable<System.DateTime> OCAN_DT_ANEXO { get; set; }
        public string OCAN_NM_TITULO { get; set; }
        public string OCAN_AQ_ARQUIVO { get; set; }
        public int OCAN_IN_TIPO { get; set; }
        public System.DateTime OCAN_DT_CADASTRO { get; set; }
        public int OCAN_IN_ATIVO { get; set; }
    
        public virtual OCORRENCIA OCORRENCIA { get; set; }
        public virtual OCORRENCIA_COMENTARIO OCORRENCIA_COMENTARIO { get; set; }
    }
}
