//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCORRENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OCORRENCIA()
        {
            this.OCORRENCIA_ANEXO = new HashSet<OCORRENCIA_ANEXO>();
            this.OCORRENCIA_COMENTARIO = new HashSet<OCORRENCIA_COMENTARIO>();
        }
    
        public int OCOR_CD_ID { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public Nullable<int> COND_CD_ID { get; set; }
        public Nullable<int> MORA_CD_ID { get; set; }
        public int CAOC_CD_ID { get; set; }
        public System.DateTime OCOR_DT_OCORRENCIA { get; set; }
        public int OCOR_IN_STATUS { get; set; }
        public string OCOR_NM_TITULO { get; set; }
        public string OCOR_TX_TEXTO { get; set; }
        public Nullable<System.DateTime> OCOR_DT_ENCERRAMENTO { get; set; }
        public string OCOR_TX_ENCERRAMENTO { get; set; }
        public System.DateTime OCOR_DT_CADASTRO { get; set; }
        public int OCOR_IN_ATIVO { get; set; }
    
        public virtual CATEGORIA_OCORRENCIA CATEGORIA_OCORRENCIA { get; set; }
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        public virtual MORADOR MORADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCORRENCIA_ANEXO> OCORRENCIA_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCORRENCIA_COMENTARIO> OCORRENCIA_COMENTARIO { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
    }
}
