//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCORRENCIA_COMENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OCORRENCIA_COMENTARIO()
        {
            this.OCORRENCIA_ANEXO = new HashSet<OCORRENCIA_ANEXO>();
        }
    
        public int OCCO_CD_ID { get; set; }
        public int OCOR_CD_ID { get; set; }
        public System.DateTime OCCO_DT_COMENTARIO { get; set; }
        public string OCCO_TX_COMENTARIO { get; set; }
        public int OCCO_IN_STATUS { get; set; }
        public System.DateTime OCCO_DT_CADASTRO { get; set; }
        public int OCCO_IN_ATIVO { get; set; }
    
        public virtual OCORRENCIA OCORRENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCORRENCIA_ANEXO> OCORRENCIA_ANEXO { get; set; }
    }
}
