//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO_COMPRA()
        {
            this.CONTA_PAGAR = new HashSet<CONTA_PAGAR>();
        }
    
        public int PECO_CD_ID { get; set; }
        public int COND_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> FORN_CD_ID { get; set; }
        public string PECO_NM_NOME { get; set; }
        public System.DateTime PECO_DT_DATA { get; set; }
        public int PECO_IN_STATUS { get; set; }
        public Nullable<System.DateTime> PECO_DT_APROVACAO { get; set; }
        public Nullable<System.DateTime> PECO_DT_CANCELAMENTO { get; set; }
        public string PECO_NM_FORMA_PAGAMENTO { get; set; }
        public string PECO_DS_JUSTIFICATIVA { get; set; }
        public string PECO_NR_NOTA_FISCAL { get; set; }
        public Nullable<System.DateTime> PECO_DT_ALTERACAO { get; set; }
        public string PECO_TX_OBSERVACOES { get; set; }
        public int PECO_IN_ATIVO { get; set; }
        public string PECO_NR_NUMERO { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_PAGAR> CONTA_PAGAR { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
    }
}
