//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPRIETARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPRIETARIO()
        {
            this.CORPO_DIRETIVO = new HashSet<CORPO_DIRETIVO>();
        }
    
        public int PROP_CD_ID { get; set; }
        public int COND_CD_ID { get; set; }
        public int UNID_D_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string PROP_NM_NOME { get; set; }
        public string PROP_NR_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> PROP_DT_NASCIMENTO { get; set; }
        public string PROP_NM_EMAIL { get; set; }
        public int PROP_IN_MORADOR { get; set; }
        public string PROP_NM_ENDERECO { get; set; }
        public string PROP_NR_NUMERO { get; set; }
        public string PROP_NR_COMPLEMENTO { get; set; }
        public string PROP_NM_BAIRRO { get; set; }
        public string PROP_NM_CIDADE { get; set; }
        public string PROP_NR_CEP { get; set; }
        public Nullable<System.DateTime> PROP_DT_COMPRA { get; set; }
        public Nullable<System.DateTime> PROP_DT_VENDA { get; set; }
        public int PROP_IN_ATUAL { get; set; }
        public string PROP_TX_OBSERVACOES { get; set; }
        public System.DateTime PROP_DT_CADASTRO { get; set; }
        public int PROP_IN_ATIVO { get; set; }
        public string PROP_AQ_FOTO { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORPO_DIRETIVO> CORPO_DIRETIVO { get; set; }
        public virtual UF UF { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
