//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITACAO_MUDANCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITACAO_MUDANCA()
        {
            this.SOLICITACAO_MUDANCA_ANEXO = new HashSet<SOLICITACAO_MUDANCA_ANEXO>();
            this.SOLICITACAO_MUDANCA_COMENTARIO = new HashSet<SOLICITACAO_MUDANCA_COMENTARIO>();
            this.SOLICITACAO_MUDANCA_MOVIMENTO = new HashSet<SOLICITACAO_MUDANCA_MOVIMENTO>();
        }
    
        public int SOMU_CD_ID { get; set; }
        public Nullable<int> COND_CD_ID { get; set; }
        public int UNID_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime SOMU_DT_MUDANCA { get; set; }
        public Nullable<int> SOMU_NR_DURACAO { get; set; }
        public int SOMU_IN_ENTRADA_SAIDA { get; set; }
        public int SOMU_IN_VETADA { get; set; }
        public int SOMU_IN_APROVACAO { get; set; }
        public int SOMU_IN_SUSENSA { get; set; }
        public int SOMU_IN_EXECUTADA { get; set; }
        public string SOMU_DS_OBSERVACOES { get; set; }
        public System.DateTime SOMU_DT_CADASTRO { get; set; }
        public int SOMU_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> SOMU_DT_APROVACAO { get; set; }
        public Nullable<System.DateTime> SOMU_DT_EXECUCAO_INICIO { get; set; }
        public Nullable<System.DateTime> SOMU_DT_EXECUCAO_FINAL { get; set; }
        public Nullable<System.DateTime> SOMU_DT_CRIACAO { get; set; }
        public Nullable<int> SOMU_IN_STATUS { get; set; }
        public Nullable<System.DateTime> SOMU_DT_VETADA { get; set; }
        public Nullable<System.DateTime> SOMU_DT_SUSPENSA { get; set; }
        public Nullable<int> SOMU_IN_ANALISE { get; set; }
        public string SOMU_NR_PLACA_CAMINHAO { get; set; }
        public string SOMU_NM_EMPRESA_MUDANCA { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITACAO_MUDANCA_ANEXO> SOLICITACAO_MUDANCA_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITACAO_MUDANCA_COMENTARIO> SOLICITACAO_MUDANCA_COMENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITACAO_MUDANCA_MOVIMENTO> SOLICITACAO_MUDANCA_MOVIMENTO { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
