//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITACAO_MUDANCA_MOVIMENTO
    {
        public int SOMV_CD_ID { get; set; }
        public int SOMU_CD_ID { get; set; }
        public Nullable<System.DateTime> SOMV_DT_ENVIO { get; set; }
        public Nullable<System.DateTime> SOMV_DT_RESPOSTA { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
    
        public virtual SOLICITACAO_MUDANCA SOLICITACAO_MUDANCA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
