//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONE
    {
        public int TELE_CD_ID { get; set; }
        public int COND_CD_ID { get; set; }
        public Nullable<int> RAAT_CD_ID { get; set; }
        public Nullable<int> CATE_CD_ID { get; set; }
        public string TELE_NM_NOME { get; set; }
        public string TELA_NM_CONTATO { get; set; }
        public string TELE_NR_DDD_FIXO { get; set; }
        public string TELE_NR_FIXO { get; set; }
        public string TELE_NR_DDD_MOVEL { get; set; }
        public string TELR_NR_MOVEL { get; set; }
        public string TELE_NM_ENDERECO { get; set; }
        public string TELE_NM_BAIRRO { get; set; }
        public string TELE_NM_CIDADE { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string TELE_NR_CEP { get; set; }
        public System.DateTime TELE_DT_CADASTRO { get; set; }
        public int TELE_IN_ATIVO { get; set; }
        public string TELE_NR_TELEFONE { get; set; }
        public string TELE_NR_CELULAR { get; set; }
    
        public virtual CATEGORIA_TELEFONE CATEGORIA_TELEFONE { get; set; }
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        public virtual RAMO_ATIVIDADE RAMO_ATIVIDADE { get; set; }
        public virtual UF UF { get; set; }
    }
}
