//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONE_EMERGENCIA
    {
        public int TEEM_CD_ID { get; set; }
        public int COND_CD_ID { get; set; }
        public string TEEM_NM_NOME { get; set; }
        public string TEEM_NR_TELEFONE { get; set; }
        public int TEEM_IN_ATIVO { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
    }
}
