//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIDADE()
        {
            this.AMBIENTE_CHAVE = new HashSet<AMBIENTE_CHAVE>();
            this.AUTORIZACAO_ACESSO = new HashSet<AUTORIZACAO_ACESSO>();
            this.CONTROLE_VEICULO = new HashSet<CONTROLE_VEICULO>();
            this.DOCUMENTO = new HashSet<DOCUMENTO>();
            this.ENCOMENDA = new HashSet<ENCOMENDA>();
            this.ENTRADA_SAIDA = new HashSet<ENTRADA_SAIDA>();
            this.LISTA_CONVIDADO = new HashSet<LISTA_CONVIDADO>();
            this.LISTA_NEGRA = new HashSet<LISTA_NEGRA>();
            this.MORADOR = new HashSet<MORADOR>();
            this.NOTIFICACAO = new HashSet<NOTIFICACAO>();
            this.OCORRENCIA = new HashSet<OCORRENCIA>();
            this.PROPRIETARIO = new HashSet<PROPRIETARIO>();
            this.RESERVA = new HashSet<RESERVA>();
            this.SOLICITACAO_MUDANCA = new HashSet<SOLICITACAO_MUDANCA>();
            this.TAXA_CONDOMINIO = new HashSet<TAXA_CONDOMINIO>();
            this.USUARIO = new HashSet<USUARIO>();
            this.VAGA_UNIDADE = new HashSet<VAGA_UNIDADE>();
            this.VEICULO = new HashSet<VEICULO>();
        }
    
        public int UNID_CD_ID { get; set; }
        public int COND_CD_ID { get; set; }
        public int TIUN_CD_ID { get; set; }
        public Nullable<int> TORR_CD_ID { get; set; }
        public string UNID_NR_NUMERO { get; set; }
        public string UNID_NM_TORRE { get; set; }
        public string UNID_NR_BLOCO { get; set; }
        public Nullable<int> UNID_NR_VAGAS { get; set; }
        public int UNID_IN_ALUGADO { get; set; }
        public Nullable<System.DateTime> UNID_DT_ULTIMA_MUDANCA { get; set; }
        public Nullable<decimal> UNID_NR_FRACAO_IDEAL { get; set; }
        public string UNID_TX_OBSERVACOES { get; set; }
        public System.DateTime UNID_DT_CADASTRO { get; set; }
        public int UNID_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMBIENTE_CHAVE> AMBIENTE_CHAVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTORIZACAO_ACESSO> AUTORIZACAO_ACESSO { get; set; }
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROLE_VEICULO> CONTROLE_VEICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCOMENDA> ENCOMENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTRADA_SAIDA> ENTRADA_SAIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_CONVIDADO> LISTA_CONVIDADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_NEGRA> LISTA_NEGRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MORADOR> MORADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICACAO> NOTIFICACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCORRENCIA> OCORRENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPRIETARIO> PROPRIETARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITACAO_MUDANCA> SOLICITACAO_MUDANCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAXA_CONDOMINIO> TAXA_CONDOMINIO { get; set; }
        public virtual TIPO_UNIDADE TIPO_UNIDADE { get; set; }
        public virtual TORRE TORRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VAGA_UNIDADE> VAGA_UNIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEICULO> VEICULO { get; set; }
    }
}
