//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_CONTROLE_ENTRADA
    {
        public int USCE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime USCE_DT_PASSAGEM { get; set; }
        public int USCE_IN_SENTIDO { get; set; }
        public string USCE_CD_TERMINAL { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
