//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VAGA()
        {
            this.VAGA_UNIDADE = new HashSet<VAGA_UNIDADE>();
        }
    
        public int VAGA_CD_ID { get; set; }
        public Nullable<int> COND_CD_ID { get; set; }
        public string VAGA_NR_NUMERO { get; set; }
        public string VAGA_NR_ANDAR { get; set; }
        public string VAGA_NR_TORRE { get; set; }
        public System.DateTime VAGA_DT_CADASTRO { get; set; }
        public int VAGA_IN_ATIVO { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VAGA_UNIDADE> VAGA_UNIDADE { get; set; }
    }
}
