//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAGA_UNIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VAGA_UNIDADE()
        {
            this.VEICULO = new HashSet<VEICULO>();
        }
    
        public int VAUN_CD_ID { get; set; }
        public int VAGA_CD_ID { get; set; }
        public int UNID_CD_ID { get; set; }
        public Nullable<System.DateTime> VAUN_DT_SORTEIO { get; set; }
        public System.DateTime VAUN_DT_CADASTRO { get; set; }
        public int VAUN_IN_ATIVO { get; set; }
    
        public virtual UNIDADE UNIDADE { get; set; }
        public virtual VAGA VAGA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEICULO> VEICULO { get; set; }
    }
}
