//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULO_ANEXO
    {
        public int VEAN_CD_ID { get; set; }
        public int VEIC_CD_ID { get; set; }
        public string VEAN_NM_TITULO { get; set; }
        public int VEAN_IN_TIPO { get; set; }
        public System.DateTime VEAN_DT_ANEXO { get; set; }
        public string VEAN_AQ_ARQUIVO { get; set; }
        public int VEAN_IN_ATIVO { get; set; }
    
        public virtual VEICULO VEICULO { get; set; }
    }
}
